on:
  push:
    branches:
      - main
      - init_repo

permissions:
  contents: write
  pull-requests: write

name: release-please

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: release
        uses: googleapis/release-please-action@v4
        with:
          release-type: python
          target-branch: ${{ github.ref_name }}
      - uses: actions/checkout@v4
      - name: tag major and minor versions
        run: |
          TAG_NAME=v${{ steps.release.outputs.major }}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git tag -a "$TAG_NAME" -m "Release $TAG_NAME"
          git push --tags
