---
name: release

on:
  push:
    tags:
      - '*'
  workflow_dispatch:
jobs:
  pypi-publish:
    name: Upload release to PyPI
    runs-on: ubuntu-latest
    environment:
      name: release
    permissions:
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - name: Build a package
        run: |
            pip install pdm
            pdm build
      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
